export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/vSrR7pq1wtPw85XpiOrdNcYdtUb.jpg",
    genre_ids: [18],
    id: 239526,
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Sueños de libertad",
    overview: "Dónde está la pequeña marmota de ortigal",
    popularity: 1929.348,
    poster_path: "/95RVeMWMvk97PBW0msryIJC32XD.jpg",
    first_air_date: "2024-02-25",
    name: "Sueños de libertad",
    vote_average: 7,
    vote_count: 13,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    backdrop_path: "/oKfIivK3Q3Sv19x78FvljefifPu.jpg",
    id: 89427,
    name: "The Countryside",
    original_name: "El pueblo",
    overview:
      "A group of urbanites flee the city for different reasons: existential, economic crisis, need for fresh air, search for peace, inspiration to compose ... The intention of these strangers is to settle in an abandoned town and start their lives from scratch, but when they arrive they discover that there are still some neighbors: rural people with a very different way of seeing life.",
    poster_path: "/w3pJC3leDFQnXsDzHWTqvY7SyMp.jpg",
    media_type: "tv",
    adult: false,
    original_language: "es",
    genre_ids: [35],
    popularity: 37.74,
    first_air_date: "2019-05-14",
    vote_average: 7.638,
    vote_count: 29,
    origin_country: ["ES"],
  },
  {
    backdrop_path: "/yMAZSN3t48O9UaBSmNGkcKcqLT4.jpg",
    id: 214160,
    name: "Found",
    original_name: "Found",
    overview:
      "In any given year, more than 600,000 people are reported missing in the U.S. Of these reported cases, more than half of the missing people are people of color, too easily neglected by the system. Gabi Mosely, a former missing person herself, now specializes in PR and leads a crisis management team that seeks out these missing people. But unbeknownst to anyone, Mosely is hiding a dark secret of her own.",
    poster_path: "/gY2JkiLZVBPxCfpqK8FcoiCR2Em.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18, 80],
    popularity: 66.995,
    first_air_date: "2023-10-03",
    vote_average: 6.9,
    vote_count: 39,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/pR0z4pM0o8oODPdugFG4wq48UXs.jpg",
    id: 213220,
    name: "Urban Horror",
    original_name: "都市懼集",
    overview:
      "Do you often feel inexplicably disturbed in this cold, unconcerned city? Those things we are used to but not specifically noticed are not caused by supernatural or spiritual phenomena, but the daily, under-the-surface crises sparked by the fear, ignorance and indifference around us. This is a series without ghosts, monsters, supernatural or sci-fi components. Every story in Urban Horror is happening around us...",
    poster_path: "/vG7cmUDBvNQDa2pX3yRQSxmprab.jpg",
    media_type: "tv",
    adult: false,
    original_language: "zh",
    genre_ids: [18],
    popularity: 140.543,
    first_air_date: "2024-07-12",
    vote_average: 9.6,
    vote_count: 5,
    origin_country: ["TW"],
  },
  {
    backdrop_path: "/uCY1j1YqfDWRbbS7hJwd9szX1sJ.jpg",
    id: 237480,
    name: "No Rancho Fundo",
    original_name: "No Rancho Fundo",
    overview: "",
    poster_path: "/eONkvEahSQJan1HTzWJKjvaMe29.jpg",
    media_type: "tv",
    adult: false,
    original_language: "pt",
    genre_ids: [10766, 18, 35],
    popularity: 845.085,
    first_air_date: "2024-04-15",
    vote_average: 4.912,
    vote_count: 18,
    origin_country: ["BR"],
  },
  {
    backdrop_path: "/8yQjxIlAeVeqkuBKq3FUQGVqfIB.jpg",
    id: 206586,
    name: "The Walking Dead: The Ones Who Live",
    original_name: "The Walking Dead: The Ones Who Live",
    overview:
      "The love story of Rick Grimes and Michonne is changed by a changed world. Kept apart by distance. By an unstoppable power. Can they find each other and who they were in a situation unlike any they've ever known?",
    poster_path: "/ywbacot78IuNhGW4uVZPxxxVTkm.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 18],
    popularity: 170.083,
    first_air_date: "2024-02-25",
    vote_average: 8.07,
    vote_count: 400,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_name: "Breaking Bad",
    overview:
      "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18, 80],
    popularity: 646.256,
    first_air_date: "2008-01-20",
    vote_average: 8.913,
    vote_count: 14057,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    id: 100088,
    name: "The Last of Us",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18],
    popularity: 225.757,
    first_air_date: "2023-01-15",
    vote_average: 8.6,
    vote_count: 4952,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/foGkPxpw9h8zln81j63mix5B7m8.jpg",
    id: 71912,
    name: "The Witcher",
    original_name: "The Witcher",
    overview:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    poster_path: "/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 18, 10759],
    popularity: 226.479,
    first_air_date: "2019-12-20",
    vote_average: 8.068,
    vote_count: 5720,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/aDBRtunw49UF4XmqfyNuD9nlYIu.jpg",
    id: 63174,
    name: "Lucifer",
    original_name: "Lucifer",
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    poster_path: "/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [80, 10765],
    popularity: 513.413,
    first_air_date: "2016-01-25",
    vote_average: 8.467,
    vote_count: 14536,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/m5CggjJuFc08QCuKz54znHP6spJ.jpg",
    id: 108978,
    name: "Reacher",
    original_name: "Reacher",
    overview:
      "Jack Reacher, a veteran military police investigator, has just recently entered civilian life. Reacher is a drifter, carrying no phone and the barest of essentials as he travels the country and explores the nation he once served.",
    poster_path: "/jFuH0md41x5mB4qj5344mSmtHrO.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10759, 80, 18],
    popularity: 289.173,
    first_air_date: "2022-02-03",
    vote_average: 8.073,
    vote_count: 1715,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/2yDV0xLyqW88dn5qE7YCRnoYmfy.jpg",
    id: 4613,
    name: "Band of Brothers",
    original_name: "Band of Brothers",
    overview:
      "Drawn from interviews with survivors of Easy Company, as well as their journals and letters, Band of Brothers chronicles the experiences of these men from paratrooper training in Georgia through the end of the war. As an elite rifle company parachuting into Normandy early on D-Day morning, participants in the Battle of the Bulge, and witness to the horrors of war, the men of Easy knew extraordinary bravery and extraordinary fear - and became the stuff of legend. Based on Stephen E. Ambrose's acclaimed book of the same name.",
    poster_path: "/8JMXquNmdMUy2n2RgW8gfOM0O3l.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18, 10768],
    popularity: 147.809,
    first_air_date: "2001-09-09",
    vote_average: 8.5,
    vote_count: 3456,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 18, 10759],
    popularity: 1012.885,
    first_air_date: "2011-04-17",
    vote_average: 8.454,
    vote_count: 23717,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/4d0tMAk49gqbVwgvtQjCriBwyb8.jpg",
    id: 106379,
    name: "Fallout",
    original_name: "Fallout",
    overview:
      "The story of haves and have-nots in a world in which there’s almost nothing left to have. 200 years after the apocalypse, the gentle denizens of luxury fallout shelters are forced to return to the irradiated hellscape their ancestors left behind — and are shocked to discover an incredibly complex, gleefully weird, and highly violent universe waiting for them.",
    poster_path: "/AnsSKR9LuK0T9bAOcPVA3PUvyWj.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 10759, 18],
    popularity: 223.784,
    first_air_date: "2024-04-10",
    vote_average: 8.332,
    vote_count: 1366,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
    id: 125988,
    name: "Silo",
    original_name: "Silo",
    overview:
      "In a ruined and toxic future, a community exists in a giant underground silo that plunges hundreds of stories deep. There, men and women live in a society full of regulations they believe are meant to protect them.",
    poster_path: "/zBx1X06G1OlndbXTCZI13FECNz2.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 18],
    popularity: 176.184,
    first_air_date: "2023-05-04",
    vote_average: 8.187,
    vote_count: 898,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/2MaumbgBlW1NoPo3ZJO38A6v7OS.jpg",
    id: 66732,
    name: "Stranger Things",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18, 10765, 9648, 10759],
    popularity: 407.397,
    first_air_date: "2016-07-15",
    vote_average: 8.605,
    vote_count: 17400,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    id: 94997,
    name: "House of the Dragon",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    poster_path: "/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 18, 10759],
    popularity: 1196.512,
    first_air_date: "2022-08-21",
    vote_average: 8.396,
    vote_count: 4808,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/34OGjFEbHj0E3lE2w0iTUVq0CBz.jpg",
    id: 87739,
    name: "The Queen's Gambit",
    original_name: "The Queen's Gambit",
    overview:
      "In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.",
    poster_path: "/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18],
    popularity: 81.965,
    first_air_date: "2020-10-23",
    vote_average: 8.486,
    vote_count: 4427,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/6MuYkNgyhPczfPSp7qqeUxBUZ8j.jpg",
    id: 84773,
    name: "The Lord of the Rings: The Rings of Power",
    original_name: "The Lord of the Rings: The Rings of Power",
    overview:
      "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
    poster_path: "/eTQLv1sjLhDBPwI2u0qaqV51HWU.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10759, 10765, 18],
    popularity: 435.867,
    first_air_date: "2022-09-01",
    vote_average: 7.347,
    vote_count: 2607,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/4XbQb5YoWK9oMrlQdKwtZ1ccpC8.jpg",
    id: 97400,
    name: "Midnight Mass",
    original_name: "Midnight Mass",
    overview:
      "An unsettling omen washes ashore in the wake of the storm. Later, when the locals gather for a potluck, tragedy strikes – and a miracle occurs.",
    poster_path: "/iYoMZYVD775MtBYJfv6OGY1FsnL.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [9648, 18],
    popularity: 62.274,
    first_air_date: "2021-09-24",
    vote_average: 7.547,
    vote_count: 858,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/uQUHCqxHsG9blvtCoL7vluMG9Jp.jpg",
    id: 118357,
    name: "1883",
    original_name: "1883",
    overview:
      "Follow the Dutton family as they embark on a journey west through the Great Plains toward the last bastion of untamed America. A stark retelling of Western expansion, and an intense study of one family fleeing poverty to seek a better future in America’s promised land — Montana.",
    poster_path: "/waLbm384SQDwLTCn6ttPqQS5kfV.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18, 37],
    popularity: 123.74,
    first_air_date: "2021-12-19",
    vote_average: 8.3,
    vote_count: 559,
    origin_country: ["US"],
  },
];
